title: My blog
author: Joseph
email: jiangshaohua.j@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another day of lightweight self-improvement. Hope I can gain power and knowledge as time goes by.

# social links
twitter_username: not often used # DO NOT include the @ character, or else the build will fail!
github_username:  Joseph Jiang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
